spring:
  application:
    name: ServerPulse
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devdb
    username: sa
    password: password

  profiles:
    active: dev

jwt:
  secret:  53A73E5A73F12E56A73E5A73F12E56A73E5A73F12E56A73E5A73F12E56
  token:
    expirationInMillis: 3600000