spring:
  application:
    name: ServerPulse
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devdb
    username: sa
    password: password

  profiles:
    active: dev

jwt:
  secret: "${JWT_SECRET:defaultSecret}"
  token:
    expirationInMillis: 3600000